import { NodeType } from "@/types";

export const NODE_LABELS: Record<NodeType, string> = {
  imageInput: "Image Input",
  audioInput: "Audio Input",
  videoInput: "Video Input",
  annotation: "Annotate",
  prompt: "Prompt",
  array: "Array",
  promptConstructor: "Prompt Constructor",
  nanoBanana: "Generate Image",
  generateVideo: "Generate Video",
  generateAudio: "Generate Audio",
  generate3d: "Generate 3D",
  llmGenerate: "LLM Generate",
  splitGrid: "Split Grid",
  output: "Output",
  outputGallery: "Output Gallery",
  imageCompare: "Image Compare",
  videoStitch: "Video Stitch",
  easeCurve: "Ease Curve",
  videoTrim: "Video Trim",
  videoFrameGrab: "Frame Grab",
  router: "Router",
  switch: "Switch",
  conditionalSwitch: "Conditional Switch",
  crop: "Crop Image",
  subflow: "Subflow",
  floatInput: "Float Input",
  glbViewer: "3D Viewer",
};
